### ISSUE TITLE
Question: Can I have arrows on the left and right side?

### ISSUE THREAD

**Issue by fourcolors** [OrangeXC/vue-coverflow#10]
I have three images. One large in the center and two small on each side of that large one. I would like to have arrows to cycle through the images with associated captions. Is this possible?

**Comment by OrangeXC** [comment]
emm...
Not currently available，this component have some problem，
I suggest you to  https://github.com/surmon-china/vue-awesome-swiper

I will improve this component in the future

Thanks to your issue
