### ISSUE TITLE
键盘操作和触摸屏支持？

### ISSUE THREAD

**Issue by iVanilla** [OrangeXC/vue-coverflow#11]
现在只能通过点击图片来切换，不够方便，希望能支持电脑键盘左右方向键操作和手机 / 平板的触摸屏滑动操作。

**Comment by OrangeXC** [comment]
@iVanilla 快一年没更新代码了，好多陈旧的遗留问题，有好点子欢迎提 pr

**Comment by iVanilla** [comment]
@OrangeXC 还有一个是切换图片的事件，不过修 bug 我大概帮不上忙了，因为水平有限。
