### ISSUE TITLE
windows下import该文件报错

### ISSUE THREAD

**Issue by sparGuan** [OrangeXC/vue-coverflow#20]
![image](https://user-images.githubusercontent.com/28480563/44322351-868d2900-a47f-11e8-91c7-13eccd04b22b.png)
![image](https://user-images.githubusercontent.com/28480563/44322374-8e4ccd80-a47f-11e8-8edb-6e9b1f8da20d.png)

**Comment by sparGuan** [comment]
哈哈，我已经把它从node-module里面抽出来做成自己的组件了
还有一个小问题了，新图片加进去的时候没有update



![2j31 6 xfgdz0zydl9 k22](https://user-images.githubusercontent.com/28480563/44332352-6ae54b00-a49e-11e8-9477-e593e69f7b25.png)

**Comment by sparGuan** [comment]
这是我稍微改良后的自动更新的解决方式，不合理的地方请指正
![image](https://user-images.githubusercontent.com/28480563/44402362-5ccb1500-a506-11e8-961a-3d68c2f87261.png)

**Comment by OrangeXC** [comment]
@sparGuan 不建议的话可以把这个项目 fork 下拉到你本地，改好了，直接提一个 pr
